server:
  port: 8090
spring:
  # 开启文件上传
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: c20-guanwnag-admin

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志

# oss配置
aliyun:
  oss:
    accessKeyId: LTAI5tCHkiy2v2c9vD42e9Gm
    secret: HL1AZL5trn6buMABZkdpp7qKmgREJ4
    endpoint: oss-cn-beijing.aliyuncs.com
    bucket: c20-guanwang-admin